#!/usr/bin/env bash

echo "Installing dotfiles..."
echo
dotfiles_dir=`pwd`
cd "$dotfile_dir"
git pull origin master
echo

function install {
  # Bash stuff
  ln -sf "$dotfiles_dir/bash/bash_aliases" ~/.bash_aliases
  ln -sf "$dotfiles_dir/bash/bash_functions" ~/.bash_functions
  ln -sf "$dotfiles_dir/bash/bash_profile" ~/.bash_profile
  if [ ! -f ~/.secrets ]; then
    cp "$dotfiles_dir/bash/secrets.example" ~/.secrets
    interactive_git_credentials
  fi

  # Git stuff
  ln -sf "$dotfiles_dir/git/gitconfig" ~/.gitconfig
  ln -sf "$dotfiles_dir/git/gitignore" ~/.gitignore
  ln -sf "$dotfiles_dir/git/gitk" ~/.gitk

  # Ruby stuff
  ln -sf "$dotfiles_dir/ruby/gemrc" ~/.gemrc
  ln -sf "$dotfiles_dir/ruby/irbrc" ~/.irbrc
  ln -sf "$dotfiles_dir/ruby/rspec" ~/.rspec

  # Custom binaries
  if [[ $(readlink ~/.bin) != "$dotfiles_dir/bin" ]]; then
    ln -sf "$dotfiles_dir/bin" ~/.bin
  fi

  # Sublime Text
  sublime_dir=~/Library/Application\ Support/Sublime\ Text\ 3/Packages/User/
  if [ ! -d "$sublime_dir" ]; then
    cp -r "$dotfiles_dir/sublime-text/" "$sublime_dir"
  fi

  source ~/.bash_profile

  echo "Installation completed. Enjoy!"
}

function interactive_git_credentials {
  read -e -p "What is your Git author name?" git_author_name
  sed -i -e "s/YOUR_GIT_AUTHOR_NAME/$git_author_name/g" ~/.secrets

  read -e -p "What is your Git author email?" git_author_email
  sed -i -e "s/YOUR_GIT_AUTHOR_EMAIL/$git_author_email/g" ~/.secrets
}

if [ "$1" == "--force" -o "$1" == "-f" ]; then
  install
else
  read -p "This will overwrite the existing dotfiles. Are you sure? (y/n) " -n 1
  echo
  if [[ $REPLY =~ ^[Yy]$ ]]; then
    install
  fi
fi
