#!/usr/bin/env bash

echo "Uninstalling dotfiles..."
echo
rm ~/.bash_aliases
rm ~/.bash_functions
rm ~/.bash_profile
rm ~/.gemrc
rm ~/.gitconfig
rm ~/.gitignore
rm ~/.gitk
rm ~/.irbrc
rm ~/.rspec
echo "Uninstalled!"