# Reload current shell
alias reload='source ~/.bash_profile'

# Exit
alias q='exit'

# Be polite
alias please='sudo'

# History
alias h='history'
alias hi='history | tail -20'

# Navigation
alias ..='cd ..'
alias ...='cd ../..'
alias cdd='cd -'
alias projects='cd $PROJECTS'

# List
alias l='ls -laGFh'
alias numfiles='echo $(ls -1 | wc -l)'

# Print each PATH entry on a separate line
alias path='echo -e ${PATH//:/\\n}'

# Processes
alias psa='ps aux'
alias psg='ps aux | grep $1'

# Kill
alias ka9='killall -9'
alias k9='kill -9'

# Print humanized sizes
alias df='df -h'

# Confirm before overwrite when copying
alias cp='cp -i'

# Copy public key to clipboard
alias pubkey="more ~/.ssh/id_rsa.pub | pbcopy | echo '=> Public key copied to clipboard.'"

# Print hosts file
alias hosts='more /etc/hosts'

# IP addresses
alias ip="dig +short myip.opendns.com @resolver1.opendns.com"
alias localip="ipconfig getifaddr en0"
alias ips="ifconfig -a | grep -o 'inet6\? \(\([0-9]\+\.[0-9]\+\.[0-9]\+\.[0-9]\+\)\|[a-fA-F0-9:]\+\)' | sed -e 's/inet6* //'"

# Dates
alias week='date +%V'
alias day='date +%d'

# Open apps
alias chrome="open -a google\ chrome"
alias safari="open -a safari"
alias firefox="open -a firefox"
alias spotify="open -a spotify"

# Clipboard
alias c='pbcopy'
alias p='pbpaste'

# Logs
alias tf='tail -f'
alias devlog='tail -f log/development.log'

# Requests
alias post='curl -i -X POST'
alias get='curl -i -X GET'
alias download='curl -O $1'

# Git
alias gst='git status'
alias gco='git checkout'
alias gp='git pull'
alias gd='git diff'
alias gb='git branch'
alias gs='git show'
alias gcl='git clone'

# Rails
alias rs='bundle exec rails server'
alias rc='bundle exec rails console'
alias rg='bundle exec rails generate'
alias rd='bundle exec rails destroy'
alias rr='bundle exec rails routes'
alias rt='bundle exec rake -T --all'

# RubyGems
alias gemi='gem install'
alias gemu='gem uninstall'

# Bundler
alias b='bundle'
alias be='bundle exec'
alias bi='bundle install'
alias bu='bundle update'

# SSG
alias jk='bundle exec jekyll server -w'
alias mm='bundle exec middleman server'

# Node
alias ni='npm install'
alias nu='npm update'
alias yi='yarn install'
alias yu='yarn upgrade'
