# Reload current shell
alias reload='source ~/.bash_profile'

alias q='exit'

# Be polite
alias please='sudo'

alias h='history'
alias hi='history | tail -20'

# Navigation
alias ..='cd ..'
alias ...='cd ../..'
alias cdd='cd -'
alias projects='cd $PROJECTS'

alias l='ls -laGFh'
alias numfiles='echo $(ls -1 | wc -l)'

# Print each PATH entry on a separate line
alias path='echo -e ${PATH//:/\\n}'

alias psa='ps aux'
alias psg='ps aux | grep $1'

alias ka9='killall -9'
alias k9='kill -9'

# Print humanized sizes
alias df='df -h'

# Confirm before overwrite when copying
alias cp='cp -i'

# Copy public key to clipboard
alias pubkey="more ~/.ssh/id_rsa.pub | pbcopy | echo '=> Public key copied to clipboard.'"

# Print hosts file
alias hosts='more /etc/hosts'

# IP addresses
alias ip="dig +short myip.opendns.com @resolver1.opendns.com"
alias localip="ipconfig getifaddr en1"
alias ips="ifconfig -a | grep -o 'inet6\? \(\([0-9]\+\.[0-9]\+\.[0-9]\+\.[0-9]\+\)\|[a-fA-F0-9:]\+\)' | sed -e 's/inet6* //'"

alias week='date +%V'
alias day='date +%d'

# Open apps
alias chrome="open -a google\ chrome"
alias safari="open -a safari"
alias firefox="open -a firefox"
alias skype='open -a Skype'
alias mou='open -a Mou'

# Clipboard
alias c='pbcopy'
alias p='pbpaste'

alias tf='tail -f'
alias devlog='tail -f log/development.log'

alias post='curl -i -X POST'
alias get='curl -i -X GET'

# Git
alias gst='git status'
alias gco='git checkout'
alias gd='git diff'
alias gb='git branch'
alias gs='git show'
alias gcl='git clone'

alias rb='ruby'
alias rs='rails s'
alias rc='rails c'
alias rg='rails g'
alias rd='rails d'

alias gemi='gem install --no-ri --no-rdoc'
alias gemu='gem uninstall'

alias b='bundle'
alias be='bundle exec'
alias bi='bundle install'
alias bu='bundle update'

alias rr='bundle exec rake routes'
alias rt='bundle exec rake -T --all'

alias jks='jekyll server -w'
alias jkb='jekyll build'

alias ni='npm install'
alias nu='npm uninstall'
alias nup='npm update'
