source ~/.bash_aliases
source ~/.bash_functions

if [ -f $(brew --prefix)/etc/bash_completion.d/git-completion.bash ]; then
  source $(brew --prefix)/etc/bash_completion.d/git-completion.bash
fi

if [ -f $(brew --prefix)/etc/bash_completion.d/git-prompt.sh ]; then
  source $(brew --prefix)/etc/bash_completion.d/git-prompt.sh
fi

if [ -f $(brew --prefix nvm)/nvm.sh ]; then
  source $(brew --prefix nvm)/nvm.sh
fi

# Use .secrets for stuff that you don't want to share in your public, versioned repo.
if [[ -e ~/.secrets ]]; then
  source ~/.secrets
fi

export PATH="$HOME/.bin:$HOME/.rbenv/bin:/usr/local/bin:$PATH"

export GOPATH=$HOME/workspace/golang
export PATH=$PATH:$GOPATH/bin

export EDITOR="subl -w"

export GREP_OPTIONS='--color=auto'

export HISTCONTROL=ignoredups:erasedups # no duplicate entries
shopt -s histappend                     # append to history, don't overwrite it
export HISTSIZE=5000
export HISTFILESIZE=5000

# Evaluate rbenv
eval "$(rbenv init -)"

# Define some colors
BLACK='\e[0;30m'
RED='\e[0;31m'
GREEN='\e[0;32m'
YELLOW='\e[0;33m'
BLUE='\e[0;34m'
CYAN='\e[0;36m'
RESET='\e[0m'

# Prompt style
export PS1="$YELLOW\$(ruby_version)$RESET \u: \w$CYAN\$(__git_ps1)$RED\$(git_dirty)$RESET\$ "